"""Create AbnormalBehaviorLog model

Revision ID: 14dfb040f92f
Revises: 4431a64fab91
Create Date: 2025-01-02 15:05:17.463936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14dfb040f92f'
down_revision = '4431a64fab91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abnormal_behavior_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_time', sa.DateTime(), nullable=True),
    sa.Column('cctv_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctvs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abnormal_behavior_logs')
    # ### end Alembic commands ###
