"""cctv_model retouch

Revision ID: 1a820aa8e8b1
Revises: fd24118e4a77
Create Date: 2025-01-03 09:59:14.885939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a820aa8e8b1'
down_revision = 'fd24118e4a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cctvs', schema=None) as batch_op:
        batch_op.drop_column('access_permission')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cctvs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_permission', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
