"""Add overcrowding_level and object_count to DetectionLog

Revision ID: 4431a64fab91
Revises: 9836b9bfa225
Create Date: 2025-01-02 15:02:49.915143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4431a64fab91'
down_revision = '9836b9bfa225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overcrowding_level', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('object_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_logs', schema=None) as batch_op:
        batch_op.drop_column('object_count')
        batch_op.drop_column('overcrowding_level')

    # ### end Alembic commands ###
