"""add detectionlog model

Revision ID: 77024915d5fa
Revises: 72ea0abbf9ed
Create Date: 2025-01-02 14:25:27.660708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77024915d5fa'
down_revision = '72ea0abbf9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_time', sa.DateTime(), nullable=True),
    sa.Column('cctv_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctvs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_logs')
    # ### end Alembic commands ###
