"""Add density_level to DetectionLog

Revision ID: 9836b9bfa225
Revises: 77024915d5fa
Create Date: 2025-01-02 14:37:37.298439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9836b9bfa225'
down_revision = '77024915d5fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('density_level', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_logs', schema=None) as batch_op:
        batch_op.drop_column('density_level')

    # ### end Alembic commands ###
